#!/usr/bin/env bash

SOURCES=${SOURCES-/sources}
TARGET=${TARGET-${SOURCES}}
WORKSPACE=${WORKSPACE-/workspace}

RPM_BUILD_SOURCES=$(rpmbuild --eval '%{_sourcedir}')
RPM_BUILD_RPMS=$(rpmbuild --eval '%{_rpmdir}')
RPM_BUILD_SRPMS=$(rpmbuild --eval '%{_srcrpmdir}')

EXIT_CODE=0

# make a copy
cp -R ${SOURCES}/* ${WORKSPACE}/.

# fix permissions on working copy
chown root:root ${WORKSPACE}/*

# copy any non-spec files/dirs to source directory
find ${WORKSPACE} -mindepth 1 -maxdepth 1 ! -name "*.spec" \
    -exec cp -R {} ${RPM_BUILD_SOURCES}/. \; || EXIT_CODE=1

SPECS=( $(find ${WORKSPACE} -maxdepth 1 -type f -name "*.spec") )

# install deps and fetch any external sources
# then do an RPM BUILD
for spec_file in ${SPECS[@]}; do
    dnf builddep -y ${spec_file} || EXIT_CODE=1
    spectool --sourcedir --get-files ${spec_file} || EXIT_CODE=1
    rpmbuild ${RPMBUILD_OPTS} -ba --clean ${spec_file} || EXIT_CODE=1
done

# extract RPMs
find ${RPM_BUILD_RPMS} -name "*.rpm" \
    -exec mv {} ${TARGET} \;

# extract SRPMs
find ${RPM_BUILD_SRPMS} -name "*.rpm" \
    -exec mv {} ${TARGET} \;

exit ${EXIT_CODE}